# Generated by Django 5.1.3 on 2024-11-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.CharField(max_length=24)),
                ('probability', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
    ]
